name: "Repo Lockdown"

on:
  issues:
    types: opened
  pull_request_target:
    types: opened
  schedule:
    - cron: "0 * * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          lock-pr: false
          github-token: ${{ github.token }}
          exclude-issue-created-before: ""
          exclude-issue-labels: ""
          issue-labels: ""
          issue-comment: ""
          skip-closed-issue-comment: false
          close-issue: true
          lock-issue: true
          issue-lock-reason: ""
          exclude-pr-created-before: ""
          exclude-pr-labels: ""
          pr-labels: ""
          pr-comment: ""
          skip-closed-pr-comment: false
          pr-lock-reason: ""
          process-only: ""
          log-output: false
